apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- namespace.yaml
- postgres-configmap.yaml
- postgres-secret.yaml
- postgres-service.yaml
- postgres-statefulset.yaml
- persistent-volume-claim.yaml
- todo-app-deployment.yaml
- todo-app-service.yaml
- todo-backend-deployment.yaml
- todo-backend-service.yaml
- nats.yaml
- broadcaster-deployment.yaml
- wikipedia-todo-cronjob.yaml
- postgres-backup-cronjob.yaml
- gateway.yaml
- httproute.yaml

images:
- name: broadcaster
  newName: otsoh/broadcaster
  newTag: 5fea714a20ea62944f7b1f903067211f9ad595b7
- name: todo-app
  newName: otsoh/todo-app
  newTag: 5fea714a20ea62944f7b1f903067211f9ad595b7
- name: todo-backend
  newName: otsoh/todo-backend
  newTag: 5fea714a20ea62944f7b1f903067211f9ad595b7
