apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: todo-app-pvc
      containers:
        - name: todo-app
          image: todo-app:1.5
          volumeMounts:
            - name: image-cache
              mountPath: /app/files
          env:
            - name: PORT
              value: "3000"
            - name: IMAGE_CACHE_DIR
              value: /app/files
            - name: TODO_BACKEND_URL
              value: http://todo-backend-svc:2346
