apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
- ./../../base
- namespace.yaml

patches:
- path: broadcaster-deployment.yaml
- path: gateway.yaml

images:
- name: broadcaster
  newName: otsoh/broadcaster
  newTag: e5050e551022204f5a5e77e1638a262198d83ba4
- name: todo-app
  newName: otsoh/todo-app
  newTag: e5050e551022204f5a5e77e1638a262198d83ba4
- name: todo-backend
  newName: otsoh/todo-backend
  newTag: e5050e551022204f5a5e77e1638a262198d83ba4
