apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
- ./../../base
- namespace.yaml

patches:
- path: broadcaster-deployment.yaml
- path: gateway.yaml

images:
- name: broadcaster
  newName: otsoh/broadcaster
  newTag: 1d2afaf6e1fdc22000953c74d728a1fee6789839
- name: todo-app
  newName: otsoh/todo-app
  newTag: 1d2afaf6e1fdc22000953c74d728a1fee6789839
- name: todo-backend
  newName: otsoh/todo-backend
  newTag: 1d2afaf6e1fdc22000953c74d728a1fee6789839
